version: '2'
services:
    test2csrv:
      image: node:6.11.2
      restart: always
      command: node ./test2c.js
      working_dir: /app
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - /root/bms/testkafka:/app
        - /root/bms/deploy/kafkadb/node_docker:/app/node_modules/node-rdkafka/build/Release
      environment:
        - KAFKA_HOST=192.168.2.11:9092,192.168.2.12:9092,192.168.2.13:9092
        - IndexTopic=pbmsindex
        - partitionnumber=32
