version: '2'
services:
  pkafkadb111:
    image: node:6.11.2
    restart: always
    command: node --max-old-space-size=8192 ./index.js
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/bms/deploy/kafkadb:/app
      - /root/bms/deploy/kafkadb/node_docker:/app/node_modules/node-rdkafka/build/Release
      - /root/bms/deploy/dist/log:/log
    environment:
      - istest=true
      - srvredis_host=192.168.2.19
      - DEBUG=dbh:kc
      - DEBUG_COLORS=1
      - MONGO_URL=mongodb://192.168.2.17:27007,192.168.2.18:27007/bmscatl
      - KAFKA_HOST=192.168.2.11:9092,192.168.2.12:9092,192.168.2.13:9092
      - mongos=true
      - NodeID=111
      - partitionnumber=384
      - kcmsg=1000
      - IndexTopic=pbmsindex
      - CurrentTopic=pbmsindex
      - GroupId=pbmsgid
      - logdir=/log
    network_mode: "host"
